### ISSUE TITLE
Scale Model for Photoetching

### ISSUE THREAD

**Issue by JasonFischell** [JasonFischell/FischellFancyFlashLight#4]
Do the files "Scale PCB Top" and "Scale PCB Bottom" in Mechanical look good for etching? 

[Scale PCB Bottom.pdf](https://github.com/JasonFischell/FischellFancyFlashLight/files/2618176/Scale.PCB.Bottom.pdf)
[Scale PCB Top.pdf](https://github.com/JasonFischell/FischellFancyFlashLight/files/2618177/Scale.PCB.Top.pdf)

**Comment by JasonFischell** [comment]
Update: it is now one sided. See you tomorrow at 8:30. 
[One Sided Scale Flashlight PCB.pdf](https://github.com/JasonFischell/FischellFancyFlashLight/files/2623039/One.Sided.Scale.Flashlight.PCB.pdf)

**Comment by sphaerobolus** [comment]
etched today.
